apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-and-build
spec:
  tasks:
  - name: clone-repository
    params:
    - name: url
      value: https://github.com/cloud-native-garage-method-cohort/buildah-pengli.git
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: pipeline-shared-data
  - name: build
    runAfter:
      - clone-repository
    params:
    - name: IMAGE
      value: "quay.io/pengli1707/express"
    taskRef:
      kind: Task
      name: buildah
    workspaces:
    - name: source
      workspace: pipeline-shared-data
  - name: kustomize-build
    runAfter:
    - build
    params:
    - name: image-with-tag
      value: "quay.io/pengli1707/express:$(tasks.clone-repository.results.commit)"
    - name: app-namespace
      value: "peng-li"
    - name: app-name
      value: "pengli-pipeline-from-scratch"      
    taskRef:
      kind: Task
      name: kustomize-build
    workspaces:
    - name: source
      workspace: pipeline-shared-data
  - name: test-deploy
    runAfter:
    - kustomize-build
    params:
    - name: app-namespace
      value: "peng-li"
    - name: app-name
      value: "pengli-pipeline-from-scratch"
    taskRef:
      kind: Task
      name: test-deploy
    workspaces:
    - name: source
      workspace: pipeline-shared-data    
  workspaces:
  - name: pipeline-shared-data
